### ISSUE TITLE
actix-rt: leaking memory in every request

### ISSUE THREAD

**Issue by Lesiuk** [actix/actix-net#129] opened 2020-04-09 13:50 UTC
I just compiled example from github and run apache benchmarks `ab -n 1000000 -c 64 http://127.0.0.1:8001/test/john/index.html` and memory was constantly growing. After 1 milion requests it was 3.1 GB of heap.

I could reproduce the same on my catalina macbook pro and linux server. It's like every request is leaking few KB's of memory.

**Comment by JohnTitor** [comment] 2020-04-10 09:06
> Maybe we can yank actix-rt:1.1.0 and release fixed version later on?

That makes sense. I'll do.

> Any point releasing the current version as 1.2.0-beta.1 for testing reasons?

I don't think releasing testing versions on 1.y.z makes much sense. I'd release 1.1.1 and yank 1.1.0.

@robjtede Btw, it'd be nicer to hide comments rather than deleting unless it's obvious spam or something else.

**Comment by frank-jaeger** [comment] 2020-04-28 19:16
I'm having a similar issue in actix-web, I'm getting a linear memory increase based on requests. The big difference is that I'm using actix-rt 1.0. I didn't want to open up a new issue because the issue is so similar. Please see my [example repo here](https://github.com/frank-jaeger/actix_rust_example) in order to reproduce the problem.

**Comment by frank-jaeger** [comment] 2020-04-28 21:35
Actually the program compiles actix-rt 1.1.0 even when actix-rt 1.0 is chosen. Is there any way to force 1.0 to be used?

**Comment by robjtede** [comment] 2020-04-28 21:41
> Is there any way to force 1.0 to be used

`version = "=1.0.0"`

**Comment by frank-jaeger** [comment] 2020-04-28 21:59
Thank you, I overlooked that no operator is the same as a caret. And the memory leak is fixed with this change!

**Closed** 2020-04-29 17:58 UTC

**Comment by JohnTitor** [comment] 2020-04-30 05:59
Released 1.1.1 and yanked 1.1.0. Sorry for the trouble!
