### ISSUE TITLE
Limit of max_connections is not enforced on backlog

### ISSUE THREAD

**Issue by bobrik** [actix/actix-net#216] opened 2020-11-29 01:42 UTC
Here's an example service with `max_connections` set to 2 and `backlog` of 16 (`actix-web` v3.3.0):

```rust
const MAX_CONNECTIONS: usize = 2;
const BACKLOG: i32 = 16;
const WORKERS: usize = 1;

const ADDR: &str = "127.0.0.1:8888";

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    simplelog::CombinedLogger::init(vec![simplelog::TermLogger::new(
        simplelog::LevelFilter::Info,
        simplelog::Config::default(),
        simplelog::TerminalMode::Stderr,
    )])
    .expect("logging configuration failed");

    log::info!(
        "Running server with {} workers / {} max connections / {} listen backlog on {}",
        WORKERS,
        MAX_CONNECTIONS,
        BACKLOG,
        ADDR
    );

    actix_web::HttpServer::new(move || {
        actix_web::App::new().route("/", actix_web::web::get().to(greet))
    })
    .on_connect(move |_, _| {
        log::info!(
            "number of open fds = {}",
            procfs::process::Process::myself()
                .expect("creating procfs reader failed")
                .fd_count()
                .expect("getting fd count failed")
        )
    })
    .max_connections(MAX_CONNECTIONS)
    .backlog(BACKLOG)
    .workers(WORKERS)
    .bind(ADDR)?
    .run()
    .await
}

async fn greet() -> impl actix_web::Responder {
    "howdy!\n"
}
```

One can run it:

```
$ cargo run
```

And then use the following go program to create one connection every 100ms without any requests:

```go
package main

import (
	"log"
	"net"
	"time"
)

func main() {
	i := 0
	for {
		i++

		_, err := net.Dial("tcp", "127.0.0.1:8888")
		if err != nil {
			log.Fatalf("Connection #%d failed: %s", i, err)
		}

		log.Printf("Connnection #%d succeded", i)

		time.Sleep(time.Millisecond * 100)
	}
}
```

The go program will happily churn until the end of ulimit.

What I expect from Actix is to not have more than 2 (limit) + 16 (backlog) connections open at any point, which corresponds to 22 open file descriptors (let's say under 30 for simplicity). What I see is that number gets a lot higher:

```
01:32:00 [INFO] Running server with 1 workers / 2 max connections / 16 listen backlog on 127.0.0.1:8888
01:32:00 [INFO] Starting 1 workers
01:32:00 [INFO] Starting "actix-web-service-127.0.0.1:8888" service on 127.0.0.1:8888
01:32:06 [INFO] number of open fds = 21
01:32:06 [INFO] number of open fds = 22
01:32:11 [INFO] number of open fds = 23
01:32:11 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:11 [INFO] number of open fds = 22
01:32:16 [INFO] number of open fds = 39
01:32:16 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:16 [INFO] number of open fds = 38
01:32:21 [INFO] number of open fds = 54
01:32:21 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:21 [INFO] number of open fds = 53
01:32:26 [INFO] number of open fds = 69
01:32:26 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:26 [INFO] number of open fds = 68
01:32:31 [INFO] number of open fds = 79
01:32:31 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:31 [INFO] number of open fds = 78
01:32:36 [INFO] number of open fds = 94
01:32:36 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:36 [INFO] number of open fds = 93
01:32:41 [INFO] number of open fds = 103
01:32:41 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:41 [INFO] number of open fds = 102
01:32:46 [INFO] number of open fds = 118
01:32:46 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:46 [INFO] number of open fds = 117
01:32:51 [INFO] number of open fds = 128
01:32:51 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:51 [INFO] number of open fds = 127
01:32:56 [INFO] number of open fds = 143
01:32:56 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:32:56 [INFO] number of open fds = 142
01:33:01 [INFO] number of open fds = 153
01:33:01 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:01 [INFO] number of open fds = 152
01:33:06 [INFO] number of open fds = 168
01:33:06 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:06 [INFO] number of open fds = 167
01:33:11 [INFO] number of open fds = 177
01:33:11 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:11 [INFO] number of open fds = 176
01:33:16 [INFO] number of open fds = 192
01:33:16 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:16 [INFO] number of open fds = 191
01:33:21 [INFO] number of open fds = 202
01:33:21 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:21 [INFO] number of open fds = 201
01:33:26 [INFO] number of open fds = 217
01:33:26 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:26 [INFO] number of open fds = 216
01:33:31 [INFO] number of open fds = 227
01:33:31 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:31 [INFO] number of open fds = 226
01:33:36 [INFO] number of open fds = 242
01:33:36 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:36 [INFO] number of open fds = 241
01:33:41 [INFO] number of open fds = 251
01:33:41 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:41 [INFO] number of open fds = 250
01:33:46 [INFO] number of open fds = 266
01:33:46 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:46 [INFO] number of open fds = 265
01:33:51 [INFO] number of open fds = 276
01:33:51 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:51 [INFO] number of open fds = 275
01:33:56 [INFO] number of open fds = 291
01:33:56 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:33:56 [INFO] number of open fds = 290
01:34:01 [INFO] number of open fds = 300
01:34:01 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:01 [INFO] number of open fds = 299
01:34:06 [INFO] number of open fds = 315
01:34:06 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:06 [INFO] number of open fds = 314
01:34:11 [INFO] number of open fds = 325
01:34:11 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:11 [INFO] number of open fds = 324
01:34:16 [INFO] number of open fds = 340
01:34:16 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:16 [INFO] number of open fds = 339
01:34:21 [INFO] number of open fds = 350
01:34:21 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:21 [INFO] number of open fds = 349
01:34:26 [INFO] number of open fds = 365
01:34:26 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:26 [INFO] number of open fds = 364
01:34:31 [INFO] number of open fds = 374
01:34:31 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:31 [INFO] number of open fds = 373
01:34:36 [INFO] number of open fds = 388
01:34:36 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:36 [INFO] number of open fds = 388
01:34:41 [INFO] number of open fds = 399
01:34:41 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:41 [INFO] number of open fds = 398
01:34:46 [INFO] number of open fds = 414
01:34:46 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:46 [INFO] number of open fds = 413
01:34:51 [INFO] number of open fds = 424
01:34:51 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:51 [INFO] number of open fds = 423
01:34:56 [INFO] number of open fds = 439
01:34:56 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:34:56 [INFO] number of open fds = 438
01:35:01 [INFO] number of open fds = 448
01:35:01 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:01 [INFO] number of open fds = 447
01:35:06 [INFO] number of open fds = 463
01:35:06 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:06 [INFO] number of open fds = 462
01:35:11 [INFO] number of open fds = 472
01:35:11 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:11 [INFO] number of open fds = 472
01:35:16 [INFO] number of open fds = 488
01:35:16 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:16 [INFO] number of open fds = 487
01:35:21 [INFO] number of open fds = 498
01:35:21 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:21 [INFO] number of open fds = 497
01:35:26 [INFO] number of open fds = 513
01:35:26 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:26 [INFO] number of open fds = 512
01:35:31 [INFO] number of open fds = 522
01:35:31 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:31 [INFO] number of open fds = 521
01:35:36 [INFO] number of open fds = 537
01:35:36 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:36 [INFO] number of open fds = 536
01:35:41 [INFO] number of open fds = 547
01:35:41 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:41 [INFO] number of open fds = 546
01:35:46 [INFO] number of open fds = 562
01:35:46 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:46 [INFO] number of open fds = 561
01:35:51 [INFO] number of open fds = 572
01:35:51 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:51 [INFO] number of open fds = 571
01:35:56 [INFO] number of open fds = 587
01:35:56 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:35:56 [INFO] number of open fds = 586
01:36:01 [INFO] number of open fds = 596
01:36:01 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:36:01 [INFO] number of open fds = 595
01:36:06 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:36:06 [INFO] number of open fds = 615
01:36:06 [INFO] number of open fds = 622
01:36:11 [INFO] number of open fds = 621
01:36:11 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:36:11 [INFO] number of open fds = 620
01:36:16 [INFO] number of open fds = 636
01:36:16 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
01:36:16 [INFO] number of open fds = 635
```

From what I see, backlog is getting drained faster than it should be. In `strace` output one can see (this is the very beginning of Go connection generation):

```
$ sudo strace -Tt -f -p $(pidof actix-conn-limit) -e accept4,close
strace: Process 5159 attached with 3 threads
[pid  5405] 01:38:16 accept4(6, {sa_family=AF_INET, sin_port=htons(35126), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 19 <0.000042>
[pid  5405] 01:38:16 accept4(6, 0x7fe321cf4550, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000019>
[pid  5404] 01:38:16 close(21)          = 0 <0.000023>
[pid  5404] 01:38:16 close(20)          = 0 <0.000011>
[pid  5404] 01:38:16 syscall_332(0, 0, 0, 0xfff, 0, 0x10) = -1 (errno 14) <0.000013>
[pid  5404] 01:38:16 syscall_332(0xffffffffffffff9c, 0x7fe31c006b00, 0, 0xfff, 0x7fe321eee620, 0) = 0 <0.000015>
[pid  5404] 01:38:16 close(20)          = 0 <0.000010>
[pid  5405] 01:38:17 accept4(6, {sa_family=AF_INET, sin_port=htons(35128), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 20 <0.000018>
[pid  5405] 01:38:17 accept4(6, 0x7fe321cf4550, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000017>
[pid  5404] 01:38:17 close(21)          = 0 <0.000013>
[pid  5404] 01:38:17 syscall_332(0xffffffffffffff9c, 0x7fe31c006240, 0, 0xfff, 0x7fe321eee620, 0) = 0 <0.000025>
[pid  5404] 01:38:17 close(21)          = 0 <0.000010>
[pid  5405] 01:38:17 accept4(6, {sa_family=AF_INET, sin_port=htons(35130), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 21 <0.000029>
[pid  5405] 01:38:17 accept4(6, 0x7fe321cf4550, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000012>
[pid  5405] 01:38:17 accept4(6, {sa_family=AF_INET, sin_port=htons(35132), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 22 <0.000017>
[pid  5405] 01:38:17 accept4(6, 0x7fe321cf4550, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000015>
[pid  5404] 01:38:21 close(20)          = 0 <0.000056>
[pid  5404] 01:38:21 close(20)          = 0 <0.000029>
[pid  5404] 01:38:21 syscall_332(0xffffffffffffff9c, 0x7fe31c007320, 0, 0xfff, 0x7fe321eee620, 0) = 0 <0.000019>
[pid  5404] 01:38:21 close(20)          = 0 <0.000026>
[pid  5404] 01:38:21 close(19)          = 0 <0.000033>
[pid  5404] 01:38:21 close(19)          = 0 <0.000033>
[pid  5404] 01:38:21 syscall_332(0xffffffffffffff9c, 0x7fe31c02ae30, 0, 0xfff, 0x7fe321eee620, 0) = 0 <0.000018>
[pid  5404] 01:38:21 close(19)          = 0 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35134), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 19 <0.000039>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35136), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 20 <0.000035>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35138), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 23 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35140), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 24 <0.000022>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35142), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 25 <0.000020>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35144), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 26 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35146), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 27 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35148), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 28 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35150), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 29 <0.000021>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35152), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 30 <0.000020>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35154), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 31 <0.000020>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35156), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 32 <0.000015>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35158), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 33 <0.000017>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35160), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 34 <0.000031>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35162), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 35 <0.000018>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35164), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 36 <0.000016>
[pid  5405] 01:38:21 accept4(6, {sa_family=AF_INET, sin_port=htons(35166), sin_addr=inet_addr("127.0.0.1")}, [128->16], SOCK_CLOEXEC) = 37 <0.000015>
[pid  5405] 01:38:21 accept4(6, 0x7fe321cf4550, [128], SOCK_CLOEXEC) = -1 EAGAIN (Resource temporarily unavailable) <0.000018>
```

In my mind `max_connections` should never allow more than 2 consecutive `accept4` without a `close` between them.

**Comment by fakeshadow** [comment] 2021-04-07 01:00
I added a test for maxconn recently and from what I see it work as expected.
https://github.com/actix/actix-net/blob/5961eb892e894db036168bb50ef9f3235d2780b1/actix-server/tests/test_server.rs#L196

Closing this for now and please ping me or re-open if the above test have any problem.

**Comment by bobrik** [comment] 2021-04-08 03:31
I don't think this is fixed, I can still replicate the behavior.

Updated `main.rs`:

```rust
const MAX_CONNECTIONS: usize = 2;
const BACKLOG: i32 = 16;
const WORKERS: usize = 1;

const ADDR: &str = "127.0.0.1:8888";

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    simplelog::CombinedLogger::init(vec![simplelog::TermLogger::new(
        simplelog::LevelFilter::Info,
        simplelog::Config::default(),
        simplelog::TerminalMode::Stderr,
    )])
    .expect("logging configuration failed");

    log::info!(
        "Running server with {} workers / {} max connections / {} listen backlog on {}",
        WORKERS,
        MAX_CONNECTIONS,
        BACKLOG,
        ADDR
    );

    actix_web::HttpServer::new(move || {
        actix_web::App::new().route("/", actix_web::web::get().to(greet))
    })
    .on_connect(move |_, _| {
        log::info!(
            "number of open fds = {}",
            procfs::process::Process::myself()
                .expect("creating procfs reader failed")
                .fd_count()
                .expect("getting fd count failed")
        )
    })
    .max_connections(MAX_CONNECTIONS)
    .backlog(BACKLOG)
    .workers(WORKERS)
    .bind(ADDR)?
    .run()
    .await
}

async fn greet() -> impl actix_web::Responder {
    "howdy!\n"
}
```

Updated `Cargo.toml`:

```toml
[package]
name = "actix-max-connections"
version = "0.1.0"
authors = ["Ivan Babrou <github@ivan.computer>"]
edition = "2018"

[dependencies]
actix-web = { version = "3" }
simplelog = { version = "0.9" }
log = { version = "0.4" }
procfs = { version = "0.9" }
```

Logs:

```
03:27:50 [INFO] Running server with 1 workers / 2 max connections / 16 listen backlog on 127.0.0.1:8888
03:27:50 [INFO] Starting 1 workers
03:27:50 [INFO] Starting "actix-web-service-127.0.0.1:8888" service on 127.0.0.1:8888
03:27:52 [INFO] number of open fds = 21
03:27:52 [INFO] number of open fds = 22
03:27:57 [INFO] number of open fds = 23
03:27:57 [INFO] number of open fds = 22
03:27:57 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
03:28:02 [INFO] number of open fds = 37
03:28:02 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
03:28:02 [INFO] number of open fds = 36
03:28:07 [INFO] number of open fds = 51
03:28:07 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
03:28:07 [INFO] number of open fds = 50
03:28:12 [INFO] number of open fds = 61
03:28:12 [INFO] Accepting connections on 127.0.0.1:8888 has been resumed
03:28:12 [INFO] number of open fds = 60
03:28:17 [INFO] number of open fds = 75
03:28:17 [INFO] number of open fds = 74
...
```

**Comment by fakeshadow** [comment] 2021-04-08 03:34
I'm not saying it's "fixed". I'm saying test show it works as intended both to the description of API and internal logic.

**Comment by bobrik** [comment] 2021-04-08 04:02
It may work great in your test, but it in reality I see more connections accepted than I allowed and you can replicate that with the code I provided. Please let me know if there's something wrong with my example.

Maybe it's because in tests you have a single threaded runtime doing everything, while in my real program I have `accept()` in a different thread, maybe it's something else.

**Comment by fakeshadow** [comment] 2021-04-08 04:07
In reality you should not count fd for concurrent testing. How do you know it's accurate or how do you know it's not other issues that leaking them?

"My" test use an atomic counter to count how many connections are accepted by one worker. It remove as much as side effect as possible. 

You want to test on sure thing instead of "maybes". Accept thread is single thread. It runs on it's own regardless how many other threads you have or what runtime you are on.

**Comment by fakeshadow** [comment] 2021-04-08 04:14
Just to be clear I'm not saying there is no issue. You issue clearly exists. It's just from the test it should have nothing to do with maxconn unless Rust has serious problem(like a unsound implementation of atomic premitive.)

We may want to see other places for the cause of issue but I'm pretty sure it's not maxconn.

**Comment by bobrik** [comment] 2021-04-08 04:46
There's an unbounded queue of connections between accept thread and workers. After worker reaches the max number of allowed connections it signals to accept thread that it is no longer available. Next time it's available, the accept queue sends as many connections down the unbounded queue as it can until worker picks up one connection to be able to say it's full again. Worker never sees more than it requested, but sockets still leak into the queue.

**Comment by fakeshadow** [comment] 2021-04-08 05:04
I don't believe it's true. It's when server enters "backpressure" that it would forcely push into the unbounded channel. At this point all sockets are deregistered so there is no new connections can be accepted. It's when any worker is available that sockets would re-registered.

There is indeed on problem with `accept_one` method though. It should return with some state and break `accept` method on first enter of `backpressure`. Or `accept` should loop on condition like `while !self.backpressure`.

**Comment by fakeshadow** [comment] 2021-04-08 06:11
https://github.com/actix/actix-net/pull/322

**Comment by fakeshadow** [comment] 2021-04-09 20:36
I don't believe this issue should be re-opened. The issue itself has nothing to do with maxconn and maxconn is working as intended.

The issue itself is about what the server would do when backpressure. Drain backlog or not? Drop connection on the drain or keep them?

The issue need a re-wording to properly reflex the problem or be a new one.

**Closed by fakeshadow** 2021-04-09 20:36 UTC

**Comment by robjtede** [comment] 2021-04-09 21:29
No problem. New issue describing the particular problem with back pressure then.

**Comment by fakeshadow** [comment] 2021-04-19 05:25
https://github.com/actix/actix-net/pull/343

This PR would fix this issue. 
But there is a catch that every request would have a couple more atomic operation no matter you use limit or not (in practical).
 I don't think there is a way to get rid of this additional overhead(lower one time could be possible).
