### ISSUE TITLE
when backpressure happen, the uds file can not be rebuild

### ISSUE THREAD

**Issue by Right2Left** [actix/actix-net#97] opened 2020-02-18 03:08 UTC
https://github.com/actix/actix-net/blob/4f2910c6b301032d09bc2cedd0f259bb008788e1/actix-server/src/socket.rs#L137

Hi, in my project just found that, when server is restarting, but clients is still always retry connect.
In server, get in accept fuc before WorkerAvailability, so it check all worker is not available in accept_one then into backpressure, cleanup file path.
though WorkerAvailability soon, but client can not request anymore.

is that a bug or some configure need to set?

**Comment by fakeshadow** [comment] 2020-11-01 09:51
Sorry if I don't follow you. But is the desire behavior is to only clean the file when shutting down the server?

**Comment by fakeshadow** [comment] 2021-04-20 05:15
Since there is no further talk happen I would close this for now.

I think I have an idea of what the problem is but since I don't use uds much I'm not sure if it would fix the problem in the right way.

Please ping me for re-open if you have the same issue and want to help see it fixed.

**Closed by fakeshadow** 2021-04-20 05:15 UTC
Labels: bug
